import { type PropsWithChildren } from "react";
import { type Metadata } from "next";
import fonts from "@/lib/fonts";
import ThemeProvider from "@/components/ThemeProvider";
import ThemeToggler from "@/components/ThemeToggler";
import QueryClientProvider from "@/components/QueryClientProvider";
import Toaster from "@/components/Toaster";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={fonts} suppressHydrationWarning>
      <body className="font-inter text-md h-full min-h-svh w-full bg-white leading-normal font-normal text-neutral-950 not-italic antialiased dark:bg-neutral-900 dark:text-neutral-100">
        <ThemeProvider
          enableSystem
          disableTransitionOnChange
          defaultTheme="system"
        >
          <ThemeToggler />
          <QueryClientProvider>{children}</QueryClientProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
