import type { PropsWithChildren } from "react";
import type { Metadata } from "next";
import fonts from "@/lib/fonts";
import ThemeProvider from "@/components/ThemeProvider";
import ThemeToggler from "@/components/ThemeToggler";
import QueryClientProvider from "@/components/QueryClientProvider";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={fonts} suppressHydrationWarning>
      <body className="font-inter text-carbon-700 dark:bg-carbon-900 dark:text-carbon-400 h-full min-h-screen w-full bg-white text-base leading-normal font-normal not-italic antialiased">
        <ThemeProvider
          enableSystem
          disableTransitionOnChange
          defaultTheme="system"
          attribute="class"
        >
          <ThemeToggler />
          <QueryClientProvider>{children}</QueryClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
