import { Suspense, type PropsWithChildren } from "react";
import { type Metadata } from "next";
import fonts from "@/lib/fonts";
import QueryClientProvider from "@/components/QueryClientProvider";
import ThemeProvider from "@/components/ThemeProvider";
import ThemeToggler from "@/components/ThemeToggler";
import Toaster from "@/components/Toaster";
import Loader from "@/components/Loader";
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={fonts} suppressHydrationWarning>
      <body className="h-full min-h-screen w-screen bg-neutral-50 font-sans text-base leading-normal font-normal text-neutral-500 antialiased dark:bg-neutral-950 dark:text-neutral-500">
        <QueryClientProvider>
          <ThemeProvider
            enableSystem
            disableTransitionOnChange
            defaultTheme="system"
          >
            <ThemeToggler />
            <Suspense fallback={<Loader />}>{children}</Suspense>
          </ThemeProvider>
        </QueryClientProvider>
        <Toaster />
      </body>
    </html>
  );
}
